{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-app.fullname" . }}-ingress
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.host | quote }}
    secretName: {{ include "my-app.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hosts.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "my-app.fullname" . }}-websvc
                port:
                  number: 80
          {{- end }}
{{- end }}
